### ISSUE TITLE
NetworkDispatcher exception

### ISSUE THREAD

**Issue by Darktilldawn** [SocraticPhoenix/VoteRight#1]
I get this error in the console and so far I've yet been able to get it working.
- http://pastebin.com/DwpYVsXH

Also get another error here
- http://pastebin.com/Me9B4gnw

And a Vote receiving error here
- http://pastebin.com/vYhNYh2N

**Comment by SocraticPhoenix** [comment]
This error is in Votifier. I'll see if I can do anything about it

**Comment by Darktilldawn** [comment]
Yeah your voting plugin works Perfect as it should when sending a simulated vote and receiving the rewards in game. Just got Votifier problems I guess so makes it untestable with a real vote.

**Comment by SocraticPhoenix** [comment]
I'll try and update votifier myself

**Comment by SocraticPhoenix** [comment]
hmm, odd, @Darktilldawn what version of sponge are you using?

**Comment by Darktilldawn** [comment]
I'm using Sponge 878 currently.

**Comment by SocraticPhoenix** [comment]
ok

**Comment by SocraticPhoenix** [comment]
@Darktilldawn 
Okay, so I looked at Votifier, and there doesn't seem to be any issue... Ensure you are running the most recent version of sponge, and the appropriate forge version. In addition, I tried to tweak a very small thing in Votifier to see if it would do anything, and that is now in the .zip file downloaded from the plugin thread. If the issue persists, post it here: https://github.com/clienthax/VotifierSponge
