### ISSUE TITLE
Possible failure to load plugin

### ISSUE THREAD

**Issue by sibomots** [SocraticPhoenix/VoteRight#4]
I was debugging why the Votifier tests were failing and then I checked the forge logs

https://gist.github.com/sibomots/4c8e7c7ae349dee60553

It looks as if the Votifier plugin isn't initializing ?

Is this a VoteRight issue?  The Votifier plugin gets installed with the VoteRight ?

Test results on SpongeForge
spongeforge-1.8-1577-2.1-DEV-936.jar

Ideas?

**Comment by Darktilldawn** [comment]
Yes votifier is broke and needs an update, Want me to link you the updated version? He'll need it as well I guess so let m esend it to him

**Comment by sibomots** [comment]
Yes, please do so.

**Comment by SocraticPhoenix** [comment]
This is not a VoteRight problem - VoteRight is loaded after Votifier.
