### ISSUE TITLE
Triggers are being run asynchronously causing ConcurrentModificationException's

### ISSUE THREAD

**Issue by bloodmc** [SocraticPhoenix/VoteRight#5]
I had a few admins report crashes to Sponge about constant ConcurrentModificationException crashes. I looked into it and it was caused by them adding triggers in VoteRight to give items/spawn entities. The issue is caused by VoteRight executing everything asynchronously which is bad for anything that requires running on the main thread such as spawning. I'll have a full stack trace shortly as I just pushed another change to Sponge for users to get the stack trace when it happens.

I assume its caused by this

https://github.com/SocraticPhoenix/VoteRight/blob/master/src/main/java/com/gmail/socraticphoenix/sponge/voteright/VoteListener.java#L70

It isn't safe to assume ANY trigger added by a user will be thread safe.

Full stack trace can be found here

http://pastebin.com/raw/28Z2KhcM

**Comment by SocraticPhoenix** [comment]
Hmm... odd. The line you linked only runs a task for logging, which returns to the main thread to do the logging anyways. My guess is that I messed up the task in one of the Trigger classes themselves... I'll check it out.

**Comment by SocraticPhoenix** [comment]
Okay, I think I've figured it out. This is an issue in Star API, so I'm closing it here and re-opening it there.

**Comment by bloodmc** [comment]
@SocraticPhoenix I don't see how it's an issue with the API. A user is able to setup a trigger using any command they wish. These triggers are being scheduling async by your plugin which is the issue. To solve the issue, the task needs to be either scheduled on the main thread or an option needs to be added to allow a user to not run a trigger async.

**Comment by SocraticPhoenix** [comment]
@bloodmc 
It's an issue with Star due to some caching it does with information used in VoteRight. In VR, triggers are NEVER run async. If the player is online, the trigger is simply run in the listener. If the player is offline, the UUID is fetched and then the task is transferred to the main thread.

**Comment by bloodmc** [comment]
Ok great thanks.
